DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 96
  TEST:
    BATCH_SIZE: 96
  NUM_WORKERS: 4

OPTIM:
  NAME: 'sgd'
  LR: 0.005
  MAX_EPOCH: 60
  LR_SCHEDULER: 'cosine'

TRAINER:
  CAUSALFD:
    ALPHA: 0.55
    BETA: 0.2
    MIX: 'crossdomain'
    BALANCED_WEIGHT: 0.5

# ALPHA: 0.45
# BETA: 0.25