DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 32
  TEST:
    BATCH_SIZE: 32
  NUM_WORKERS: 4

OPTIM:
  NAME: 'sgd'
  LR: 0.001
  MAX_EPOCH: 50
  LR_SCHEDULER: 'cosine'

TRAINER:
  CAUSALFD:
    ALPHA: 0.4
    BETA: 0.6

# ALPHA: 0.35 with art, product, real-world; 0.7 with clip-art
# BETA: 0.7