DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 32
  TEST:
    BATCH_SIZE: 32
  NUM_WORKERS: 4

OPTIM:
  NAME: 'sgd'
  LR: 0.001
  MAX_EPOCH: 50
  LR_SCHEDULER: 'cosine'

TRAINER:
  CAUSALFD:
    ALPHA: 0.45
    BETA: 0.25
    MIX: 'crossdomain'
    BALANCED_WEIGHT: 0.5

# ALPHA: 0.45
# BETA: 0.45