DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 32
  TEST:
    BATCH_SIZE: 32
  NUM_WORKERS: 4

OPTIM:
  NAME: 'sgd'
  LR: 0.001
  MAX_EPOCH: 50
  LR_SCHEDULER: 'cosine'

TRAINER:
  CAUSALFD:
    ALPHA: 0.75
    BETA: 0.2
    MIX: 'crossdomain'
    BALANCED_WEIGHT: 0.5

# ALPHA: 0.75
# BETA: 0.25

# HOW TO CHOOSE BETA:
# Case 1: Original Images + 3 Other Images --> BETA: 0.3
# Case 2: Original Images + 6 Other Images --> BETA: 0.15
# Case 3: Original Images + 4 Other Images --> BETA: 0.25
# Case 4: Original Images + 2 Other Images --> BETA: 0.35