INPUT:
  SIZE: (224, 224)
  TRANSFORMS: ["random_flip", "random_translation", "colorjitter", "randomgrayscale"]

DATASET:
  NAME: "OfficeHomeDG"

MODEL:
  BACKBONE:
    NAME: "resnet18"
    PRETRAINED: True